name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Job para todos los microservicios con documentación
  test-and-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      matrix:
        service: [gateway, usuarios, pagos, catalogo]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm install
        else
          cd microservicios/${{ matrix.service }} && npm install
        fi
    
    - name: Run ESLint
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm run lint || echo "Linting failed for ${{ matrix.service }}"
        else
          cd microservicios/${{ matrix.service }} && npm run lint || echo "Linting failed for ${{ matrix.service }}"
        fi
    
    - name: Run tests
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm test || echo "Tests failed for ${{ matrix.service }}"
        elif [ "${{ matrix.service }}" = "usuarios" ]; then
          cd microservicios/${{ matrix.service }} && npm test || echo "Tests failed for ${{ matrix.service }}"
        else
          echo "Tests skipped for ${{ matrix.service }}"
        fi
    
    - name: Generate documentation
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm run docs || echo "No docs script found for ${{ matrix.service }}"
        else
          cd microservicios/${{ matrix.service }} && npm run docs || echo "No docs script found for ${{ matrix.service }}"
        fi
    
    - name: Prepare documentation artifact
      run: |
        # Crear carpeta temporal para artifacts
        mkdir -p artifact-docs
        
        # Copiar documentación según el servicio
        if [ "${{ matrix.service }}" = "gateway" ]; then
          if [ -d "gateway/docs" ]; then
            cp -r gateway/docs/* artifact-docs/ || echo "No docs found in gateway"
          else
            echo "Gateway docs directory not found" > artifact-docs/README.txt
          fi
        else
          if [ -d "microservicios/${{ matrix.service }}/docs" ]; then
            cp -r microservicios/${{ matrix.service }}/docs/* artifact-docs/ || echo "No docs found in ${{ matrix.service }}"
          else
            echo "${{ matrix.service }} docs directory not found" > artifact-docs/README.txt
          fi
        fi
        
        # Crear archivo de información del artifact
        echo "Documentation for ${{ matrix.service }} microservice" > artifact-docs/SERVICE_INFO.txt
        echo "Generated on: $(date)" >> artifact-docs/SERVICE_INFO.txt
        echo "Service: ${{ matrix.service }}" >> artifact-docs/SERVICE_INFO.txt
        
        # Listar contenido para verificación
        echo "Artifact contents:"
        ls -la artifact-docs/
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.service }}-documentation
        path: artifact-docs/
        retention-days: 30

  # Job para frontend (separado porque no necesita documentación de microservicios)
  frontend-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: cd frontend && npm install
    
    - name: Run ESLint
      run: cd frontend && npm run lint || echo "Linting failed for frontend"
    
    - name: Build frontend
      run: cd frontend && npm run build || echo "Build completed for frontend"
