name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [gateway, usuarios, pagos, catalogo, frontend]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm install
        elif [ "${{ matrix.service }}" = "usuarios" ]; then
          cd microservicios/usuarios && npm install
        elif [ "${{ matrix.service }}" = "pagos" ]; then
          cd microservicios/pagos && npm install
        elif [ "${{ matrix.service }}" = "catalogo" ]; then
          cd microservicios/catalogo && npm install
        elif [ "${{ matrix.service }}" = "frontend" ]; then
          cd frontend && npm install
        fi
    
    - name: Run linter
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm run lint || echo "No lint script found"
        elif [ "${{ matrix.service }}" = "usuarios" ]; then
          cd microservicios/usuarios && npm run lint || echo "No lint script found"
        elif [ "${{ matrix.service }}" = "pagos" ]; then
          cd microservicios/pagos && npm run lint || echo "No lint script found"
        elif [ "${{ matrix.service }}" = "catalogo" ]; then
          cd microservicios/catalogo && npm run lint || echo "No lint script found"
        elif [ "${{ matrix.service }}" = "frontend" ]; then
          cd frontend && npm run lint || echo "No lint script found"
        fi
    
    - name: Run tests
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm test -- --coverage --passWithNoTests
        elif [ "${{ matrix.service }}" = "usuarios" ]; then
          cd microservicios/usuarios && npm test -- --coverage --passWithNoTests
        elif [ "${{ matrix.service }}" = "pagos" ]; then
          cd microservicios/pagos && npm test -- --coverage --passWithNoTests || echo "No tests configured"
        elif [ "${{ matrix.service }}" = "catalogo" ]; then
          cd microservicios/catalogo && npm test -- --coverage --passWithNoTests || echo "No tests configured"
        elif [ "${{ matrix.service }}" = "frontend" ]; then
          cd frontend && npm test -- --coverage --passWithNoTests || echo "No tests configured"
        fi
    
    - name: Generate documentation
      run: |
        if [ "${{ matrix.service }}" = "gateway" ]; then
          cd gateway && npm run docs || echo "No docs script found"
        elif [ "${{ matrix.service }}" = "usuarios" ]; then
          cd microservicios/usuarios && npm run docs || echo "No docs script found"
        elif [ "${{ matrix.service }}" = "pagos" ]; then
          cd microservicios/pagos && npm run docs || echo "No docs script found"
        elif [ "${{ matrix.service }}" = "catalogo" ]; then
          cd microservicios/catalogo && npm run docs || echo "No docs script found"
        elif [ "${{ matrix.service }}" = "frontend" ]; then
          cd frontend && npm run docs || echo "No docs script found"
        fi
